drop table if exists bookmarks;

create table bookmarks (
    id integer primary key generated by default as identity,
    title text not null,
    url text not null,
    description text,
    rating integer not null
);

insert into bookmarks (title, url, description, rating)
values
    ('Google', 'www.google.com', 'A search engine', 5),
    ('Facebook', 'www.facebook.com', 'A social media platform', 3),
    ('Twitter', 'www.twitter.com', 'Another social media platform', 4),
    ('Reddit', 'www.reddit.com', 'The front page of the internet', 4),
    ('Thinkful', 'www.thinkful.com', 'A coding bootcamp', 5),
    ('Yahoo', 'www.yahoo.com', 'An older search engine', 3),
    ('Yahoo answers', 'www.answers.yahoo.com', 'Most questions answered in minutes', 3),
    ('Roll20', 'app.roll20.net', 'An online tabletop gaming platform', 5),
    ('Youtube', 'www.youtube.com', 'A site for hosting and sharing videos', 4),
    ('Gmail', 'www.gmail.com', 'A popular email service', 5);